language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
matrix:
  allow_failures:
    - python: "3.3"
# command to install dependencies
install:
  - pip install . --use-mirrors
# command to run tests, e.g. python setup.py test
script:
  - nosetests
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 pypc; fi
cache: apt
