language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
install: "pip install . --use-mirrors"
# command to run tests, e.g. python setup.py test
script: nosetests
